### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by ByblackSun** [funtime-foxy1/ShowLootOnPlanet#1]
![20240124180733_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/2aa8f2f9-7848-4d7b-ac53-982817abeb1b)

The fonts overlap and I wish the fonts could be a little smaller.

**Comment by funfoxrr** [comment]
I'll soon publish an update with more settings such as offset, font size, and more. Thanks for the notice and 1.0.3 should be out soon. I'll send a message here when an update is released.

**Comment by funfoxrr** [comment]
Mod updated to 1.0.3, more options! Have fun :)
