### ISSUE TITLE
Compatibility with ShipLootPlus by PXC

### ISSUE THREAD

**Issue by cntrik** [funtime-foxy1/ShowLootOnPlanet#3]
I love this mod idea I do know you support compat with ShipLoot by tinyhoot however [ShipLootPlus](https://thunderstore.io/c/lethal-company/p/PXC/ShipLootPlus/) by PXC is a Rewrite of the OG ShipLoot and enhanced with more customization which I think this mod would be amazing with. Currently it is on top of the Ship info 
![download (1)](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/11052983/bac1b052-6bae-431d-92f9-db3ca1379e20)

**Comment by funfoxrr** [comment]
As mentioned in Issue #1, Update 1.0.3 will have customization including offset, font size, etc. Thanks for the notice!

**Comment by funfoxrr** [comment]
Mod updated to 1.03, more settings! Have fun :)
