### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by ByblackSun** [funtime-foxy1/ShowLootOnPlanet#4]
There is no response after pressing the scan button. I am not sure if it is a problem with this mod. I have never had any impression of this problem before.

normal circumstances
![20240126231440_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/28312123-f3be-46ff-b55e-70c1a47568ec)

abnormal
![20240126231359_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/680e2b87-cd88-4d1a-b4bc-a7ddc501fbd6)

**Comment by funfoxrr** [comment]
There is a bug with the mod, making scanning not happening. Not sure how to fix, I'll work on the issue.

**Comment by funfoxrr** [comment]
I have added the dependency: https://thunderstore.io/c/lethal-company/p/ThePotato/scanForItemsFix/ which should fix the bug. If not, please post another issue or message me on discord! (funfoxrr)
