### ISSUE TITLE
scrap value issue

### ISSUE THREAD

**Issue by ByblackSun** [funtime-foxy1/ShowLootOnPlanet#5]
![20240130063944_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/992d2fed-6e50-4f71-a3f7-50c9c543ce19)
![20240130064325_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/236445fc-f6a2-4e52-b134-572a0502eaf5)
![20240130064334_1](https://github.com/funtime-foxy1/ShowLootOnPlanet/assets/155830927/70a652a9-7bf5-420e-9bf2-bd3c4187f1f6)

Why is the value so different? Is it related to other mod?

I have used this to get the terminal to display the correct amount
https://thunderstore.io/c/lethal-company/p/Nebulaetrix/ScanFix/

**Comment by funfoxrr** [comment]
Then, the mod is modifying the terminal code, not my mod's code. I'll try to incorporate the mod into this mod.

**Comment by funfoxrr** [comment]
I have modified the code and made it work like the mod! New version: 1.0.5
